package com.example.pingtai.mapper;

import com.example.pingtai.domain.entity.PerfamazonDemand;
import com.example.pingtai.domain.entity.PerfamazonDemandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface PerfamazonDemandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    int countByExample(PerfamazonDemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    int deleteByExample(PerfamazonDemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    int insert(PerfamazonDemand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    int insertSelective(PerfamazonDemand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    List<PerfamazonDemand> selectByExample(PerfamazonDemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    PerfamazonDemand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PerfamazonDemand record, @Param("example") PerfamazonDemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:32 CST 2020
     */
    int updateByExample(@Param("record") PerfamazonDemand record, @Param("example") PerfamazonDemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:33 CST 2020
     */
    int updateByPrimaryKeySelective(PerfamazonDemand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perfamazon_demand
     *
     * @mbggenerated Wed Sep 09 15:22:33 CST 2020
     */
    int updateByPrimaryKey(PerfamazonDemand record);
}
